version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 666:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./:/usr/share/nginx/html
