FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./index.php /usr/share/nginx/html/index.html
VOLUME ./index.html /usr/share/nginx/html/index.html
VOLUME ./index.php /usr/share/nginx/html/index.html
