version: '3'

services:
app:
    build:
      context: .
      dockerfile: Dockerfile
      image: php:7.2-fmp
      container_name: site-content_php_1
  nginx:
    image: nginx:latest
    container_name: site-content_nginx_1
    ports:
      - 666:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./:/usr/share/nginx/html
